language: bash
dist: "trusty"
before_install:
  - pip install --user scrapy
  - pip install --user unidecode
before_script:
    - bash setup.sh
script:
    - bash job.sh
after_success:
    - bash postsuccess.sh
